---
#
# Upload the required tests.
#
# The extra uploads (extra.uploads) and configuration (ansible_vars.yml) are
# already loaded by the calling upload_extra role, so we do not reload them here.
#

#
# If we are pulling a file
#
- name: Upload the extra files
  include_role:
    name: actual_upload_extra
  vars:
    extra_file_upload: "{{ extra_file }}"
  when: extra_file != "none"
  loop:  "{{ extra.uploads | default([], true) }}"
  loop_control:
    loop_var: extra_file

