---
#
# Upload and install any requested rpms.
#

- name: include_rpms
  include_vars:
    file: "{{ working_dir }}/upload_rpms.yml"
    name: rpms

#
# Upload and install each rpm.  A value of "none" is the sentinel written by
# burden when no rpms were requested, so skip it.
#
- name: perform rpm upload
  include_role:
    name: rpm_upload_and_install
  vars:
    rpm: "{{ rpm_file }}"
    results_file: "{{ results_file }}"
  when: rpm_file != "none"
  loop:  "{{ rpms.rpm }}"
  loop_control:
    loop_var: rpm_file
