---
# tasks file for install_packages
#

#
# Install packages on rhel/amazon images.
#
- name: install rhel packages
  block:
  - name: Remove any existing status file.
    file:
      path: "{{ results_file }}"
      state: absent
  - name: install yum packages
    yum:
      name: "{{ pkg_install }}"
      state: latest
    register: install_results
  - name: Report Success
    lineinfile:
       path: "{{ results_file }}"
       line: "status: success"
       create: yes
  rescue:
    - name: Error check
      include_role:
        name: package_install_error
      vars:
        rtc_val: true
        packages: "{{ pkg_install }}"
  when: config_info.os_vendor == "rhel"

- name: install amazon packages
  block:
  - name: Remove any existing status file.
    file:
      path: "{{ results_file }}"
      state: absent
  - name: install yum packages
    shell: "yum -y install {{ pkg_install | join(' ') }}"
    ignore_errors: yes
    register: install_results
  - name: Error check
    include_role:
      name: package_install_error
    vars:
      rtc_val: "{{ install_results.rc != 0 }}"
      packages: "{{ pkg_install }}"
  when: config_info.os_vendor == "amazon"

#
# Install packages on ubuntu images.
#
- name: Install ubuntu packages
  block:
  - name: Remove any existing status file.
    file:
      path: "{{ results_file }}"
      state: absent
  - name: ubuntu package install
    shell: "apt -y install {{ pkg_install | join(' ') }}"
    ignore_errors: yes
    register: install_results
  - name: Error check
    include_role:
      name: package_install_error
    vars:
      rtc_val: "{{ install_results.rc != 0 }}"
      packages: "{{ pkg_install }}"
  when: config_info.os_vendor == "ubuntu"

#
# Install packages on SUSE images.
#
# The zypper module comes from community.general.  If at any point we find a case it's not already installed we'll have to update the installer script.
#
- name: install SUSE packages
  block:
  - name: Remove any existing status file.
    file:
      path: "{{ results_file }}"
      state: absent
  - name: install zypper packages
    zypper:
      name: "{{ pkg_install }}"
      state: latest
    register: install_results
    until: install_results is succeeded
    retries: 5
    delay: 10
  - name: Report Success
    lineinfile:
       path: "{{ results_file }}"
       line: "status: success"
       create: yes
  rescue:
    - name: Error check
      include_role:
        name: package_install_error
      vars:
        rtc_val: true
        packages: "{{ pkg_install }}"
  when: config_info.os_vendor == "suse"
