---
# tasks file for install_packages
#

#
# Install packages on rhel/amazon images.
#
- name: install rhel packages
  block:
  - name: Remove any existing status file.
    shell: "rm -f {{ results_file }}"
  - name: install yum packages
    yum:
      name: "{{ pkg_install }}"
      state: latest
    register: install_results
  - name: Report Success
    lineinfile:
       path: "{{ results_file }}"
       line: "status: sucess"
       create: yes
  rescue:
    - name: Report Error
      lineinfile:
         path: "{{ results_file }}"
         line: "status: failed"
         create: yes
  any_errors_fatal: true
  when: config_info.os_vendor == "rhel"

- name: install amazon packages
  block:
  - name: install yum packages
    shell: "yum -y install `echo {{ pkg_install }} | sed \"s/\\[//g\" | sed \"s/]//g\" | sed \"s/,//g\"`"
    ignore_errors: yes
    register: install_results
  - name: Error check
    include_role:
      name: package_install_error
    vars:
      rtc_val: "{{ install_results.rc }}"
      packages: "{{ pkg_install }}"
  when: config_info.os_vendor == "amazon"

#
# Install packages on ubuntu images.
#
- name: Install ubuntu packages
  block:
  - name: ubuntu package install
    shell: "apt -y install `echo {{ pkg_install }} | sed \"s/\\[//g\" | sed \"s/]//g\" | sed \"s/,//g\"`"
    ignore_errors: yes
    register: install_results
  - name: Error check
    include_role:
      name: package_install_error
    vars:
      rtc_val: "{{ install_results.rc }}"
      packages: "{{ pkg_install }}"
  when: config_info.os_vendor == "ubuntu"
