- name: Get options for {{ tool }}
  ansible.builtin.command:
    cmd: echo {{ options[tool] | default('') }} --interval={{ interval }}
  changed_when: false
  register: option

- name: Display tool options
  ansible.builtin.debug:
    var: option
