- name: Output options for {{ tool }} to /tmp/{{ tool }}.options
  ansible.builtin.lineinfile:
    line: "{{ options[tool] | default('') }} --interval={{ interval }}"
    path: /tmp/{{ tool }}.options
    state: present

- name: Fetch options for {{ tool }} from /tmp/{{ tool }}.options
  ansible.builtin.slurp:
    src: /tmp/{{ tool }}.options
  register: options


- name: Display {{ tool }} options
  ansible.builtin.debug:
    var: options['content'] | b64decode

- name: Register {{ tool }} in {{ group }} tool group
  ansible.builtin.command:
    cmd: pbench-register-tool --name={{ tool }} --group {{ group }} -- {{ options }}
