---
# tasks file for recording the status of the operation
#
- name: Record status of run
  lineinfile:
    path: "{{ status_file }}"
    line: "status: {{ 'failed' if results is failed else 'success' }}"
    create: yes
