reboot_system: "no"
test_run_from: "remote"
os_supported: all
pbench_required: "no"
pbench_local_results: "no"
test_run_from: "remote"
storage_required: "no"
network_required: "no"
java_required: "no"
archive_results: "yes"
test_specific: ""
upload_extra: "none"
post_script: "none"
pre_setup: "none"
