--- 
java_defs:
  java_config1:
    java_version: java-11
    amazon: java-11-amazon-corretto-headless
    rhel: java-11-openjdk-devel
    ubuntu: openjdk-11-jre-headless
    suse: java-11-openjdk-devel
  java_config2:
    java_version: java-8
    amazon: java-1.8.0-openjdk
    rhel: java-1.8.0-openjdk-devel
    ubuntu: openjdk-8-jdk
    suse: java-1_8_0-openjdk-devel
  java_config3:
    java_version: java-17
    amazon: java-17-corretto-headless
    rhel: java-17-openjdk-headless
    ubuntu: openjdk-17-jre-headless
    suse: java-17-openjdk-headless
  java_config4:
    java_version: java-21
    amazon: java-21-corretto-headless
    rhel: java-21-openjdk-headless
    ubuntu: openjdk-21-jre-headless
    suse: java-21-openjdk-headless
