test_defs:
  test1:
    test_template: linpack_template.yml
    test_name: linpack
    test_description: standard linpack test.
    archive_results: "yes"

  test2:
    test_template: linpack_template.yml
    test_name: pbench_linpack
    test_description: pbench linpack test.
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench --interleave all --pbench_user {{ config_info.user_running }}  --run_label {{ config_info.run_label }}"

  test3:
    test_template: streams_template.yml
    test_name: streams
    test_specific: "--iterations 5"

  test4:
    test_template: pig_template.yml
    test_name: pig
    test_description: Bill Gray's pig test
    archive_results: "yes"

  test5:
    test_template: specjbb_template.yml
    test_name: specjbb
    test_description: Standard specjbb test
    archive_results: "yes"

  test6:
    test_template: specjbb_template.yml
    test_name: pbench_specjbb
    test_description: pbench specjbb.
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }} --use_pbench_version"

  test7:
    test_template: fio_template.yml
    test_name: pbench_fio
    test_description: pbench fio
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench_samples 1 --disks {{ dyn_data.storage }} --pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }} --use_pbench_version --regression"
    upload_extra: "none"

  test8:
    test_template: uperf_template.yml
    test_name: uperf
    test_description: uperf
    archive_results: "yes"
    test_specific: " --client_ips {{ dyn_data.ct_uperf_server_ip }} --server_ips {{ dyn_data.ct_uperf_client_list }} --tests stream,rr --numb_jobs 1,8,16 --packet_type tcp --packet_sizes 64,16384 --time 60"

  test9:
    test_template: uperf_template.yml
    test_name: pbench_uperf
    test_description: pbench uperf
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--client_ips {{ dyn_data.ct_uperf_server_ip }} --server_ips {{ dyn_data.ct_uperf_client_list }} --tests stream,rr --numb_jobs 1,8,16 --packet_type tcp --packet_sizes 64,16384 --time 60 --pbench --pbench_user {{ config_info.user_running }} --use_pbench_version --run_label {{ config_info.run_label }}"

  test10:
    test_template: phoronix_template.yml
    test_name: phoronix
    test_description: phoronix ng test
    test_specific: ""

  test11:
    test_template: hammerdb_template.yml
    test_name: hammerdb_mariadb
    test_description: hammerdb mariadb
    test_specific: --disks {{ dyn_data.storage }} --sub_test mariadb
    archive_results: "yes"

  test12:
    test_template: hammerdb_template.yml
    test_name: hammerdb_postgres
    test_description: hammerdb postgres
    test_specific: --disks {{ dyn_data.storage }} --sub_test postgres
    archive_results: "yes"

  test13:
    test_template: hammerdb_template.yml
    test_name: hammerdb_mssql
    test_description: hammerdb mssql
    test_specific: --disks {{ dyn_data.storage }} --sub_test mssql
    archive_results: "yes"

  test14:
    test_template: reboot_measure.yml
    test_name: reboot_measure
    test_description:  Measure reboot times.
    reboot_system: "no"
    test_run_from: "local"
    os_supported: all
    rhel_pkgs: bc
    ubuntu_pkgs: none
    amazon_pkgs: none
    pbench_required: "no"
    pbench_local_results: "no"
    storage_required: "no"
    network_required: "no"
    java_required: "no"
    archive_results: "no"
    test_script_to_run: run_reboot.sh
    test_specific: --working_dir {{ working_dir }}
    upload_extra: "none"

  test15:
    test_template: autohpl.yml
    test_name: auto_hpl
    test_description:  High Performance LINPACK.

  test17:
    test_template: fio_template.yml
    test_name: fio
    test_description: straight fio
    archive_results: "yes"
    test_specific: "--disks {{ dyn_data.storage }} --regression"

  test18:
    test_template: speccpu2017_template.yml
    test_name: speccpu2017
    test_description: speccpu2017
    test_specific: "--disks {{ dyn_data.storage }} --test intrate,fprate"

  test19:
    test_template: fio_template.yml
    test_name: etcd_fio
    test_description: etcd simulation via fio, using pbench-fio
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--disks {{ dyn_data.storage }} --etcd_opts --pbench_samples 10 --pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }} --use_pbench_version"
    archive_results: "yes"

  test20:
    test_template: streams_template.yml
    test_name: pbench_streams
    test_description: Run streams via pbench.
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"

  test21:
    test_template: pig_template.yml
    test_name: pbench_pig
    test_description: Bill Gray's pig test via pbench
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_script_to_run: run_pig.sh
    test_specific: "--pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"

  test23:
    test_template: phoronix_template.yml
    test_name: pbench_phoronix
    test_description: phoronix ng test via pbench
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"

  test24:
    test_template: speccpu2017_template.yml
    test_name: pbench_speccpu2017
    test_description: speccpu2017 via pbench
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--disks {{ dyn_data.storage }} --test intrate,fprate --pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"

  test25:
    test_template: iozone_template.yml
    test_name: iozone
    test_description: iozone
    test_description: iozone
    pbench_required: "no"
    pbench_local_results: "no"
    test_specific: "--devices_to_use {{ dyn_data.storage }} "--filesys xfs,ext4,ext3  --all_test --mount_location /iozone/iozone0 --eatmem --auto"
  test26:
    test_template: iozone_template.yml
    test_name: pbench_iozone
    test_description: iozone via pbench
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--devices_to_use {{ dyn_data.storage }}  --filesys xfs --file_count_list 1,2,4 --test_type 0,1 --incache --mount_location /iozone/iozone0 --pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"

  test27:
    test_template: hammerdb_template.yml
    test_name: pbench_hammerdb_mariadb
    test_description: hammerdb mariadb via pbench
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--disks {{ dyn_data.storage }} --sub_test mariadb --pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"
    archive_results: "yes"

  test28:
    test_template: hammerdb_template.yml
    test_name: pbench_hammerdb_postgres
    test_description: hammerdb postgres
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--disks {{ dyn_data.storage }} --sub_test postgres --pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"
    archive_results: "yes"

  test29:
    test_template: hammerdb_template.yml
    test_name: pbench_hammerdb_mssql
    test_description: pbench_hammerdb mssql
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--disks {{ dyn_data.storage }} --sub_test mssql --pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"
    archive_results: "yes"

  test30:
    test_template: autohpl.yml
    test_name: pbench_auto_hpl
    test_description:  High Performance LINPACK.
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--regression --pbench --pbench_user {{ config_info.user_running }} --run_label {{ config_info.run_label }}"

  test32:
    test_template: burst_io.yml
    test_name: burst_io
    test_description: burst_io
    test_description: burst_io
    pbench_required: "no"
    pbench_local_results: "no"
    test_specific: "--disks {{ dyn_data.storage }} --opt_type read --threads 1"

  test33:
    test_template: coremark_pro_template.yml
    test_name: coremark_pro
    test_description: core mark pro test
    archive_results: "yes"
    test_specific: "--no-overrides"

  test34:
    test_template: coremark_template.yml
    test_name: coremark
    test_description: coremark test
    archive_results: "yes"

  test35:
    test_template: passmark_template.yml
    test_name: passmark
    test_description: passmark test
    archive_results: "yes"

  test36:
    test_template: coremark_pro_template.yml
    test_name: pbench_coremark_pro
    test_description: core mark pro test via pbench
    archive_results: "yes"
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench --pbench_user {{ config_info.user_running }}  --run_label {{ config_info.run_label }} --no-overrides"

  test37:
    test_template: coremark_template.yml
    test_name: pbench_coremark
    test_description: coremark test via pbench
    archive_results: "yes"
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench --pbench_user {{ config_info.user_running }}  --run_label {{ config_info.run_label }}"

  test38:
    test_template: passmark_template.yml
    test_name: pbench_passmark
    test_description: passmark test via pbench
    archive_results: "yes"
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench --pbench_user {{ config_info.user_running }}  --run_label {{ config_info.run_label }}"

  test39:
    test_template: pyperformance_template.yml
    test_name: pyperf
    test_description: pyperfotmance test
    archive_results: "yes"

  test40:
    test_template: pyperformance_template.yml
    test_name: pbench_pyperf
    test_description: pyperfotmance test
    archive_results: "yes"
    pbench_required: "yes"
    pbench_local_results: "yes"
    test_specific: "--pbench --pbench_user {{ config_info.user_running }}  --run_label {{ config_info.run_label }}"
