---

- name: AWS info file header
  copy:
    dest: "{{ working_dir }}/tf_results"
    content: |
      ---
      aws_info:
- name: Non spot record info
  block:
  - name: AWS non-spot terraform file, no network
    copy:
      dest: "{{ working_dir }}/tf_results"
      content: |
        public_dns_host0: "{{ aws_data.outputs.public_dns_host0.value }}"
        aws_instance_id0: "{{ aws_data.outputs.aws_instance_id0.value }}"
        aws_zone_id0: "{{ aws_data.outputs.aws_zoneid0.value }}"
  - name: AWS non-spot terraform file, network
    blockinfile:
      path: "{{ working_dir }}/tf_results"
      marker : ""
      insertafter: EOF
      block: |
        public_dns_host1: "{{ aws_data.outputs.public_dns_host1.value }}"
        aws_instance_id1: "{{ aws_data.outputs.aws_instance_id1.value }}"
        aws_zone_id1: "{{ aws_data.outputs.aws_zoneid1.value }}"
    when: config_info.cloud_numb_networks != 0
  when: config_info.spot_range == 0

- name: spot record info
  block:
  - name: AWS spot terraform file, no network
    copy:
      dest: "{{ working_dir }}/tf_results"
      content: |
        public_dns_host0: "{{ aws_data.outputs.public_dns_host0.value }}"
        aws_instance_id0: "{{ aws_data.outputs.aws_instance_id0.value }}"
  - name: Record the zone id for spot system
    shell: "echo aws_zone_id0: `aws ec2 describe-instances  --instance-id {{ aws_data.outputs.aws_instance_id0.value }} | grep PLACEMENT  | cut -d' ' -f 2` >> {{ working_dir }}/tf_results"
  - name: AWS non-spot terraform file, network
    block:
    - name: Add network lines
      blockinfile:
        path: "{{ working_dir }}/tf_results"
        marker : ""
        insertafter: EOF
        block: |
          public_dns_host1: "{{ aws_data.outputs.public_dns_host1.value }}"
          aws_instance_id1: "{{ aws_data.outputs.aws_instance_id1.value }}"
    - name: Record zone for spot network
      shell: "echo aws_zone_id1: `aws ec2 describe-instances  --instance-id {{ aws_data.outputs.aws_instance_id1.value }} | grep PLACEMENT  | cut -d'  ' -f 2` >> {{ working_dir }}/tf_results"
    when: config_info.cloud_numb_networks != 0
  when: config_info.spot_range != 0
