---
#
# Retrieve the vpc for the provided instance.  We need the vpc in order
# to create the networks
#
# Variables passed in:
#   working_dir: the directory we are running from.
#
- name: retrieve public vpc from terraform
  shell: "grep  \"zathras_vpc: Creation\" {{ working_dir }}/tf/terraform_apply.out | cut -d'=' -f 2 | cut -d']' -f 1"
  register: results

- name: record vpc group
  lineinfile:
    path: "{{ working_dir }}/ansible_run_vars.yml"
    line: "aws_vpc_id: {{ results.stdout }}"

- name: retrieve prvt vpc from terraform
  shell: "grep \"zathras_prvt_vpc: Creation\" {{ working_dir }}/tf/terraform_apply.out | cut -d'=' -f 2 | cut -d']' -f 1"
  register: results

- name: record prvt vpc group
  lineinfile:
    path: "{{ working_dir }}/ansible_run_vars.yml"
    line: "aws_prvt_vpc_id: {{ results.stdout }}"
