---
# tasks file for termination on failure deletion
#
#
#- name: Obtain install status
- name: Read status file
  shell: cat {{ working_dir }}/{{ status_file }} 2> /dev/null
  register: status
  ignore_errors: yes

- name: Warn on failure failure
  debug:
    msg: "{{ warning }}"
  when: '"fail" in status.stdout'
