---
# tasks file for termination on failure

- name: First,log to the error log
  cmd: "echo Fatal error: {{ exit_msg }} >> {{ working_dir }}/error_log"

- name: Aborting test
  fail:
    msg: "{{ exit_msg }}"
 
