---

- name: Create resources
  shell: |
    terraform workspace select {{ config_info.system_type }}-{{ config_info.run_label }}-{{ config_info.host_or_cloud_inst }}
    terraform apply plan.tfplan 2>&1 | tee {{ working_dir }}/tf/terraform_apply.out
  args:
    chdir: "{{ working_dir }}/tf"
  register: create
  ignore_errors: yes

- name: Report tf create
  debug:
    var: create

#
# update the return status, to be used by the calling module.  We could
# use set facts here, but chose to use a file instead for debugging purposes.
# We can not write directly out the rtc, because spot returns ok, even
# when it failed. So we need to check.
#
- name: Save the tf operation return code, success
  lineinfile:
    path: "{{ working_dir }}/tf.rtc"
    regexp: '^(.*)rtc:(.*)$'
    line: "rtc: 0"
    backrefs: yes
  when: create.rc == 0 and '"Error" not in create.stdout_lines' and '"Error" not in create.stdout'
