---
#
# Retrieve the system meta data for azure/gcp.  As AWS is via a cli not curl, we do that from 
# the aws code itseldf.
#
- name: Retrieve the azure meta data and set the tags
  block:
  - name: Grab the metada
    shell: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq > /tmp/meta_data.yml
    register: azure_meta_data
  - name: retrieve the azure metadata
    fetch:
      src: "/tmp/meta_data.yml"
      dest: "{{ working_dir }}/meta_data.yml"
      flat: yes
  when:
    - config_info.system_type == "azure"

- name: Retrieve the GCP meta data
  block:
    - name: Install jq on RHEL
      when: config_info.os_vendor == 'rhel'
      shell: yum -y install jq

    - name: Install jq on Ubuntu
      when: config_info.os_vendor == 'ubuntu'
      shell: apt-get update && apt-get install -y jq

    - name: Grab the metadata
      shell: curl -H Authorization:Bearer $(gcloud auth print-identity-token) -H Metadata-Flavor:Google 'http://metadata.google.internal/computeMetadata/v1/instance/?recursive=true' | jq > /tmp/meta_data.yml
      register: gcp_meta_data

    - name: Retrieve the GCP metadata
      fetch:
        src: "/tmp/meta_data.yml"
        dest: "{{ working_dir }}/meta_data.yml"
        flat: yes

  when:
    - config_info.system_type == "gcp"

