#!/bin/bash

cd /home/$1/pbench_setup

el8=`uname -a | grep el8`
if [ -z "$el8" ]; then
	echo install rhel7
	cp pbench.repo.ec2.rhel7 /etc/yum.repos.d/pbench.repo
	yum -y install pbench-agent-internal
else
	echo install rhel8
	cp pbench.repo.ec2.rhel8 /etc/yum.repos.d/pbench.repo
	yum -y localinstall perl-Switch-2.17-10.el8.noarch.rpm
	yum -y install pbench-agent-internal
fi
